### ISSUE TITLE
npm install - found 1 low severity vulnerability

### ISSUE THREAD

**Issue by vthwang** [poacher2k/hexo-featured-image#10]
Hi, @poacher2k,

When I tried to run `npm install`, it kept showing the error message which is shown as the following image, can you fix the error? Thanks for your help.

<img width="979" alt="Screen Shot 2020-03-09 at 5 29 04 PM" src="https://user-images.githubusercontent.com/8935531/76199913-aafc5200-622b-11ea-8998-d56db5e16eb3.png">

**Comment by poacher2k** [comment]
Hey @TingSyuanWang , thank you for the report. I have updated `hexo-fs` from 0.2 to 2.0, so I was wondering if you can try to install `hexo-featured-image@next` and see if it still works for you?

**Comment by vthwang** [comment]
@poacher2k It's working. Thanks for your kindly help.

**Comment by poacher2k** [comment]
Glad to hear! I'll publish it to the `latest` tag as soon as I get the chance :)

Edit: Done
