### ISSUE TITLE
URL construction of images w/ post_asset_folder no longer working some time between hexo 4.0.0 and hexo 5.0.2

### ISSUE THREAD

**Issue by Kritner** [poacher2k/hexo-featured-image#12]
I'm not sure how much information to provide here, but I believe something has changed with the way hexo generates between 4.0.0 and 5.0.2, in that the feature image settings I was using previously now only lead to broken images.

I'm using a `post_asset_folder`, so that images are stored similarly to: `/2021/01/01/my-post-title/image.jpg` as seen here: https://blog.kritner.com/2020/12/24/design-patterns-decorator/

where the built image address is: `https://blog.kritner.com/2020/12/24/design-patterns-decorator/cover.jpg`

The front matter is defined as such:

```yml
---
title: 'Design Patterns: Decorator'
date: 2020-12-24 10:00:00
tags:
 - programming
 - 'design patterns'
 - 'decorator pattern'
 - 'c#'
categories:
 - [programming, 'design patterns']
 - ['design patterns', 'decorator']
featured_image: cover.jpg
thumbnail: cover.jpg
---
```

It looks like so:

![image](https://user-images.githubusercontent.com/8814983/140503979-8ac85b09-6198-4924-83f2-6b208e3b0033.png)

And the current package.json:

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "4.0.0",
    "hexo-featured-image": "^0.4.3",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-twitter": "^1.0.1",
    "hexo-unsplash-credit": "^1.0.0"
  }
}
```

-----

In the process of updating my theme (icarus) and to hexo 5.0.2.

Here's a build preview of the site under the new versions: https://deploy-preview-55--lucid-murdock-407fc3.netlify.app/

where the built image address is: `https://deploy-preview-55--lucid-murdock-407fc3.netlify.app/cover.JPG`.  You'll notice that the `post_asset_folder` is seemingly being ignored for the construction of the URL, given the same configuration and front matter as the previous version.

This presents as:

![image](https://user-images.githubusercontent.com/8814983/140504682-b747df77-5b25-4bc4-9b8e-d3ff1f81851e.png)

And the new package.json:

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.0.2"
  },
  "dependencies": {
    "bulma-stylus": "0.8.0",
    "hexo": "5.0.2",
    "hexo-algolia": "^1.3.2",
    "hexo-featured-image": "^0.4.3",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-tag-twitter": "^1.0.2",
    "hexo-theme-icarus": "^4.4.0",
    "hexo-unsplash-credit": "^1.0.0"
  }
}
```

I don't know a whole lot about JS or the innerworkings of how the hexo generation occurs, but I'm guessing maybe some events that were previously hooked into may have been either changed, or their parameters changed?

**Comment by poacher2k** [comment]
Thank you for reporting this! I'll take a look as soon as I can :)

**Comment by Kritner** [comment]
I may have been mistaken, I for some reason changed in my upgrade process `feature_image` -> `cover` in the front matter, but it's been a while since I did so in my branch, so I don't recall why.  I'm trying to investigate further, but right now I'm having an issue where the "Read More" functionality on the root of the site isn't working, and all posts are showing their full content.

**Comment by Kritner** [comment]
I will close this for the moment, I don't think it's an issue, just my mistake.  If I end up actually having this issue after I figure out what's going on elsewhere (with the "Read More" stuff referenced in https://github.com/poacher2k/hexo-featured-image/issues/12#issuecomment-961915484) I may open it back up.

Sorry to have wasted your time!

**Comment by Kritner** [comment]
So I did some tinkering around with it, and put together a reproduction of the issue.

Here is the repo: https://github.com/Kritner/HexoFeaturedImageRepro

in the `main` branch, I'm using the "old" version - hexo 4.0.0, the "pasted in the source" icarus theme, and the featured-image plugin/addon, where `featured_image` is working as intended, it's visible as both a "thumbnail" and "post title".

![image](https://user-images.githubusercontent.com/8814983/140555836-55c7b3a7-857c-4eba-98e7-019d5f7f71d4.png)

In the `hexoUpgrade` [branch](https://github.com/Kritner/HexoFeaturedImageRepro/tree/hexoUpgrade), I'm using the latest hexo (5.4.0), the newest icarus theme (4.4.0 - which is now installed as a package), and featured-image plugin/addon.  In this branch, the `featured_image` no longer shows up as intended in the post title, though it does still show up as a post thumbnail.

![image](https://user-images.githubusercontent.com/8814983/140555602-3c558416-2d95-4fa1-8364-cfedd3763b61.png)

Hopefully it's something dumb I've missed, but at least there's the two minimal reproductions of "working" and "not working".

**Comment by poacher2k** [comment]
Looks like the icarus theme (and you) were never using `hexo-featured-image` in the first place :) https://github.com/Kritner/HexoFeaturedImageRepro/blob/main/themes/icarus/layout/common/article.ejs#L3-L9

To use `hexo-featured-image` you check for `<% if (post.featured_image) { %>` instead, and use `post.featured_image` as the img src instead. Not sure how to do this with the updated icarus theme though 🤷‍♂️
