### ISSUE TITLE
Featured image isn't set as preview image on social media

### ISSUE THREAD

**Issue by bonobo-d** [poacher2k/hexo-featured-image#13]
The plugin works nicely to set a featured image on a blog's post list page. However, when I link to a blog post with a featured image on Twitter or other social media, the preview tile shows one of the images contained in the post contents, instead of the featured image. I would expect the featured image to be the one shown in these cases.

Has this been considered? Would it be easy to implement?

**Comment by poacher2k** [comment]
Hi @bonobo-d ! You can accomplish this by adding something like this to your `head.ejs` or `head.pug` for your theme:

For ejs:
```ejs
<% if (page.featured_image){ %>
    <meta name="og:image" content="<%- full_url_for(page.featured_image) %>">
<% } %>
```
For pug:
```pug
if page.featured_image
  meta(name='og:image', content=full_url_for(page.featured_image))
```

I can't see that the necessary `data` is available in the [`head_begin` or `head_end` injectors](https://hexo.io/api/injector) for this to be done automatically, but I might be mistaken here as I don't know these APIs very in-depth.

**Comment by bonobo-d** [comment]
Hi @poacher2k , in the meantime I had figured out something similar. I was hoping it could be integrated seamlessly in Hexo's [open_graph](https://hexo.io/docs/helpers.html#open-graph) helper function, but I imagine it may not be worth the trouble. Thank you for the patience, I think we can close this.

**Comment by poacher2k** [comment]
> I was hoping it could be integrated seamlessly in Hexo's [open_graph](https://hexo.io/docs/helpers.html#open-graph) helper function

I guess you could pass it to the `open_graph` helper with the `image` option. This defaults to [`page.photos`](https://github.com/hexojs/hexo/blob/cb19b2938d1f7882a4cb41a98974a3d673a63b45/lib/plugins/helper/open_graph.js#L60) if no option is supplied, but adding the featured image to the photos array seems like it could potentially mess with other plugins like galleries and such.
