### ISSUE TITLE
Support for relative URLs

### ISSUE THREAD

**Issue by rberrelleza** [poacher2k/hexo-featured-image#7]
It would be useful if there was a configuration setting to make the feature image URL relative to the root of the site, instead of using the full URL:

```
current:  https://okteto.com/blog/how-to-deploy-to-okteto-cloud-with-github-actions/cover.png
desired: /blog/how-to-deploy-to-okteto-cloud-with-github-actions/cover.png
```

This would be useful for the case where the same generated HTML is used on different sites (e.g. staging vs production).

Happy to submit a PR if you think this is useful. A config setting could be added to enable this, so the default behavior remains as is.

**Comment by poacher2k** [comment]
Available in `0.4.0`, now published on `npm`
