### ISSUE TITLE
"Appears to be a git repo or submodule" on npm install

### ISSUE THREAD

**Issue by Kritner** [poacher2k/hexo-featured-image#9]
Often (but not always) i get the following error when `npm i`...

![image](https://user-images.githubusercontent.com/8814983/71325180-177e7500-24b7-11ea-969c-3b36adf907c6.png)

Looking in my node_modules folder, i can see it's grabbing a ".git" folder from the npm package, which i believe is throwing things off.

![image](https://user-images.githubusercontent.com/8814983/71325192-43015f80-24b7-11ea-8370-ba92e925579a.png)

![image](https://user-images.githubusercontent.com/8814983/71325203-5f050100-24b7-11ea-97b0-2f88a7f78121.png)

Seems that this could be corrected with a .npmignore or similar.

**Comment by poacher2k** [comment]
That's strange, as according to [the documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):

> If there’s no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file

**Comment by poacher2k** [comment]
Oh right, `.git` is of course not gitignored. I'll fix it! :)

**Comment by poacher2k** [comment]
Fix is out in `0.4.1` :+1:
